services:
  postgres:
    image: 'postgres:12-alpine'
    environment:
      - POSTGRES_DB=runnerz
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    ports:
      - '5432:5432'
